name: "github"
version: "1.3.5"
usage: "Manage chart repositories on GitHub Releases"
description: "The plugin allows to use GitHub Releases to upload, fetch charts and to work with repositories."
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/bin/helm-github.sh"
downloaders:
- command: "./bin/repo.sh"
  protocols:
  - "github"
- command: "./bin/release.sh"
  protocols:
  - "github+release"
- command: "bin/file.sh"
  protocols:
  - "github+file"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
